import type { Content } from '@/types';

export const contentData: Content[] = [
  {
    id: 9,
    title: 'Interstellar',
    type: 'Movie',
    posterUrl: 'https://placehold.co/400x600',
    aiHint: 'space travel',
    shortDescription: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    synopsis: 'When Earth becomes uninhabitable in the future, a former NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.',
    personalReview: 'A visually stunning and emotionally powerful sci-fi epic. A masterpiece from Christopher Nolan that pushes the boundaries of filmmaking and storytelling.',
    rating: 10,
    details: {
      genre: ['Sci-Fi', 'Adventure', 'Drama'],
      year: 2014,
      duration: '2h 49m',
    },
    externalLink: 'https://www.imdb.com/title/tt0816692/',
  },
  {
    id: 10,
    title: 'The Dark Knight Rises',
    type: 'Movie',
    posterUrl: 'https://placehold.co/400x600',
    aiHint: 'superhero city',
    shortDescription: 'Eight years after the Joker\'s reign of anarchy, Batman, with the help of the enigmatic Selina, is forced from his exile to save Gotham City.',
    synopsis: 'Bane, an imposing terrorist, puts Gotham City under siege and pushes Batman to his limits, forcing him to resurface after taking the fall for Harvey Dent\'s crimes.',
    personalReview: 'A spectacular conclusion to an epic trilogy. Tom Hardy\'s Bane is a formidable villain, and the scale of the action is breathtaking.',
    rating: 9.8,
    details: {
      genre: ['Action', 'Thriller', 'Superhero'],
      year: 2012,
      duration: '2h 44m',
    },
    externalLink: 'https://www.imdb.com/title/tt1345836/',
  },
  {
    id: 11,
    title: 'Oppenheimer',
    type: 'Movie',
    posterUrl: 'https://placehold.co/400x600',
    aiHint: 'atomic explosion',
    shortDescription: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.',
    synopsis: 'The story of J. Robert Oppenheimer, the theoretical physicist credited with being the "father of the atomic bomb" for his role in the Manhattan Project during World War II.',
    personalReview: 'A cinematic tour de force. Intense, gripping, and brilliantly acted. Nolan has created another masterpiece that is both a historical epic and a chilling character study.',
    rating: 9.7,
    details: {
      genre: ['Biography', 'Drama', 'History'],
      year: 2023,
      duration: '3h 0m',
    },
    externalLink: 'https://www.imdb.com/title/tt15398776/',
  },
  {
    id: 12,
    title: 'The Shawshank Redemption',
    type: 'Movie',
    posterUrl: 'https://placehold.co/400x600',
    aiHint: 'prison escape',
    shortDescription: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
    synopsis: 'Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.',
    personalReview: 'An absolute timeless classic. A story of hope, friendship, and perseverance that resonates deeply. It\'s a film everyone should see at least once.',
    rating: 9.6,
    details: {
      genre: ['Drama'],
      year: 1994,
      duration: '2h 22m',
    },
    externalLink: 'https://www.imdb.com/title/tt0111161/',
  },
  {
    id: 13,
    title: 'Maharaja',
    type: 'Movie',
    posterUrl: 'https://placehold.co/400x600',
    aiHint: 'indian barber',
    shortDescription: 'A barber seeks vengeance after his home is burglarized, telling the police that his "Lakshmi" has been stolen.',
    synopsis: 'When a barber\'s home is robbed, he mysteriously tells the police that his "Lakshmi" has been stolen, setting off a relentless quest for revenge against the man who wronged him.',
    personalReview: 'A raw and intense revenge thriller. Vijay Sethupathi delivers a powerful performance. The storytelling is gritty and keeps you on the edge of your seat.',
    rating: 9.5,
    details: {
      genre: ['Action', 'Drama', 'Thriller'],
      year: 2024,
      duration: '2h 22m',
    },
    externalLink: 'https://www.imdb.com/title/tt27478640/',
  },
  {
    id: 3,
    title: 'Breaking Bad',
    type: 'TV Show',
    posterUrl: 'https://placehold.co/400x600',
    aiHint: 'desert chemistry',
    shortDescription: 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine.',
    synopsis: 'A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family\'s future.',
    personalReview: 'One of the greatest TV shows ever made. The character development of Walter White is phenomenal, and the plot is gripping from start to finish.',
    rating: 10,
    details: {
      genre: ['Crime', 'Drama', 'Thriller'],
      year: 2008,
      episodes: 62,
    },
    externalLink: 'https://www.imdb.com/title/tt0903747/',
  },
  {
    id: 4,
    title: 'Fleabag',
    type: 'TV Show',
    posterUrl: 'https://placehold.co/400x600',
    aiHint: 'woman thinking',
    shortDescription: 'A dry-witted woman, known only as Fleabag, has no filter as she navigates life and love in London.',
    synopsis: 'A comedic and poignant look at a dry-witted, grief-riddled woman as she navigates life and love in London.',
    personalReview: 'Painfully funny and deeply moving. Phoebe Waller-Bridge is a genius. The fourth-wall breaks are used to incredible effect.',
    rating: 9.5,
    details: {
      genre: ['Comedy', 'Drama'],
      year: 2016,
      episodes: 12,
    },
    externalLink: 'https://www.imdb.com/title/tt5687612/',
  },
  {
    id: 5,
    title: 'Attack on Titan',
    type: 'Anime',
    posterUrl: 'https://placehold.co/400x600',
    aiHint: 'giant monster',
    shortDescription: 'After his hometown is destroyed, Eren Yeager vows to cleanse the earth of the giant humanoid Titans.',
    synopsis: 'In a world where humanity resides within enormous walled cities to protect themselves from gigantic man-eating humanoids known as Titans, a young boy, Eren Yeager, vows to exterminate the Titans after they bring about the destruction of his hometown and the death of his mother.',
    personalReview: 'An epic in every sense of the word. The action is breathtaking, the story is complex and full of twists, and the themes are dark and mature. A must-watch.',
    rating: 9.7,
    details: {
      genre: ['Action', 'Dark Fantasy', 'Post-apocalyptic'],
      year: 2013,
      episodes: 88,
    },
    externalLink: 'https://www.imdb.com/title/tt2560140/',
  },
  {
    id: 6,
    title: 'Steins;Gate',
    type: 'Anime',
    posterUrl: 'https://placehold.co/400x600',
    aiHint: 'time machine',
    shortDescription: 'A group of friends have customized their microwave into a device that can send text messages to the past.',
    synopsis: 'A self-proclaimed mad scientist, Rintaro Okabe, accidentally discovers a method of sending messages to the past, leading to a series of unforeseen and dangerous consequences.',
    personalReview: 'A slow burn that builds into one of the most brilliant and emotionally resonant time travel stories ever told. The characters are unforgettable.',
    rating: 9.6,
    details: {
      genre: ['Sci-Fi', 'Thriller', 'Psychological'],
      year: 2011,
      episodes: 24,
    },
    externalLink: 'https://www.imdb.com/title/tt1910272/',
  },
  {
    id: 7,
    title: 'The Office (US)',
    type: 'TV Show',
    posterUrl: 'https://placehold.co/400x600',
    aiHint: 'office workplace',
    shortDescription: 'A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.',
    synopsis: 'A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.',
    personalReview: 'The ultimate comfort show. Hilarious, heartwarming, and endlessly rewatchable. The characters feel like family.',
    rating: 8.5,
    details: {
      genre: ['Comedy', 'Mockumentary'],
      year: 2005,
      episodes: 201,
    },
    externalLink: 'https://www.imdb.com/title/tt0386676/',
  },
  {
    id: 8,
    title: 'Spirited Away',
    type: 'Anime',
    posterUrl: 'https://placehold.co/400x600',
    aiHint: 'fantasy world',
    shortDescription: 'A young girl wanders into a world of gods, witches, and spirits, and where humans are changed into beasts.',
    synopsis: 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',
    personalReview: 'A visually breathtaking and enchanting film. Studio Ghibli at its absolute best. A magical experience for all ages.',
    rating: 9.4,
    details: {
      genre: ['Animation', 'Adventure', 'Family'],
      year: 2001,
      duration: '2h 5m'
    },
    externalLink: 'https://www.imdb.com/title/tt0245429/',
  }
];
