import type { Content } from '@/types';

export const contentData: Content[] = [
  {
    id: 1,
    title: 'Inception',
    type: 'Movie',
    posterUrl: 'https://placehold.co/400x600',
    aiHint: 'abstract dreamscape',
    shortDescription: 'A thief who steals corporate secrets through use of dream-sharing technology.',
    synopsis: 'A thief who enters the dreams of others to steal their secrets gets a final chance at redemption which involves executing a dangerous plan.',
    personalReview: 'A mind-bending thriller that gets better with every watch. The visuals are stunning and the concept is incredibly original. A modern classic.',
    details: {
      genre: ['Sci-Fi', 'Thriller', 'Action'],
      year: 2010,
      duration: '2h 28m',
    },
    externalLink: 'https://www.imdb.com/title/tt1375666/',
  },
  {
    id: 2,
    title: 'Parasite',
    type: 'Movie',
    posterUrl: 'https://placehold.co/400x600',
    aiHint: 'family drama',
    shortDescription: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    synopsis: 'All unemployed, Ki-taek\'s family takes a peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.',
    personalReview: 'A masterpiece of storytelling. It perfectly blends dark comedy, drama, and thriller elements to create a powerful commentary on class struggle.',
    details: {
      genre: ['Thriller', 'Drama', 'Comedy'],
      year: 2019,
      duration: '2h 12m',
    },
    externalLink: 'https://www.imdb.com/title/tt6751668/',
  },
  {
    id: 3,
    title: 'Breaking Bad',
    type: 'TV Show',
    posterUrl: 'https://placehold.co/400x600',
    aiHint: 'desert chemistry',
    shortDescription: 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine.',
    synopsis: 'A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family\'s future.',
    personalReview: 'One of the greatest TV shows ever made. The character development of Walter White is phenomenal, and the plot is gripping from start to finish.',
    details: {
      genre: ['Crime', 'Drama', 'Thriller'],
      year: 2008,
      episodes: 62,
    },
    externalLink: 'https://www.imdb.com/title/tt0903747/',
  },
  {
    id: 4,
    title: 'Fleabag',
    type: 'TV Show',
    posterUrl: 'https://placehold.co/400x600',
    aiHint: 'woman thinking',
    shortDescription: 'A dry-witted woman, known only as Fleabag, has no filter as she navigates life and love in London.',
    synopsis: 'A comedic and poignant look at a dry-witted, grief-riddled woman as she navigates life and love in London.',
    personalReview: 'Painfully funny and deeply moving. Phoebe Waller-Bridge is a genius. The fourth-wall breaks are used to incredible effect.',
    details: {
      genre: ['Comedy', 'Drama'],
      year: 2016,
      episodes: 12,
    },
    externalLink: 'https://www.imdb.com/title/tt5687612/',
  },
  {
    id: 5,
    title: 'Attack on Titan',
    type: 'Anime',
    posterUrl: 'https://placehold.co/400x600',
    aiHint: 'giant monster',
    shortDescription: 'After his hometown is destroyed, Eren Yeager vows to cleanse the earth of the giant humanoid Titans.',
    synopsis: 'In a world where humanity resides within enormous walled cities to protect themselves from gigantic man-eating humanoids known as Titans, a young boy, Eren Yeager, vows to exterminate the Titans after they bring about the destruction of his hometown and the death of his mother.',
    personalReview: 'An epic in every sense of the word. The action is breathtaking, the story is complex and full of twists, and the themes are dark and mature. A must-watch.',
    details: {
      genre: ['Action', 'Dark Fantasy', 'Post-apocalyptic'],
      year: 2013,
      episodes: 88,
    },
    externalLink: 'https://www.imdb.com/title/tt2560140/',
  },
  {
    id: 6,
    title: 'Steins;Gate',
    type: 'Anime',
    posterUrl: 'https://placehold.co/400x600',
    aiHint: 'time machine',
    shortDescription: 'A group of friends have customized their microwave into a device that can send text messages to the past.',
    synopsis: 'A self-proclaimed mad scientist, Rintaro Okabe, accidentally discovers a method of sending messages to the past, leading to a series of unforeseen and dangerous consequences.',
    personalReview: 'A slow burn that builds into one of the most brilliant and emotionally resonant time travel stories ever told. The characters are unforgettable.',
    details: {
      genre: ['Sci-Fi', 'Thriller', 'Psychological'],
      year: 2011,
      episodes: 24,
    },
    externalLink: 'https://www.imdb.com/title/tt1910272/',
  },
  {
    id: 7,
    title: 'The Office (US)',
    type: 'TV Show',
    posterUrl: 'https://placehold.co/400x600',
    aiHint: 'office workplace',
    shortDescription: 'A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.',
    synopsis: 'A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.',
    personalReview: 'The ultimate comfort show. Hilarious, heartwarming, and endlessly rewatchable. The characters feel like family.',
    details: {
      genre: ['Comedy', 'Mockumentary'],
      year: 2005,
      episodes: 201,
    },
    externalLink: 'https://www.imdb.com/title/tt0386676/',
  },
  {
    id: 8,
    title: 'Spirited Away',
    type: 'Anime',
    posterUrl: 'https://placehold.co/400x600',
    aiHint: 'fantasy world',
    shortDescription: 'A young girl wanders into a world of gods, witches, and spirits, and where humans are changed into beasts.',
    synopsis: 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',
    personalReview: 'A visually breathtaking and enchanting film. Studio Ghibli at its absolute best. A magical experience for all ages.',
    details: {
      genre: ['Animation', 'Adventure', 'Family'],
      year: 2001,
      duration: '2h 5m'
    },
    externalLink: 'https://www.imdb.com/title/tt0245429/',
  }
];
